#! /usr/bin/env python

import sys
import os

# This is so we can run out of the source directory, no matter what
# the users current directory is.
sys.path.insert(
    0, os.path.dirname(os.path.abspath(sys.argv[0])) + "/lib")

from ruledownloader import ruledownloader

sys.exit(ruledownloader.main())
